name: "size"
on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
jobs:
    size:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
              with:
                  sudo: false
            - uses: porcellus/size-limit-action@feature/continue_on_base_branch_error
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
